import random
# print("press enter to get an OTP ")
x=random.randint(0,9)
a=random.randint(0,9)
b=random.randint(0,9)
c=random.randint(0,9)
d=random.randint(0,9)
e=random.randint(0,9)
print(x,a,b,c,d,e)
# print(x)
# print(a)
# print(b)
# print(c)
# print(d)
# print(e)
# print("helo")